### ISSUE TITLE
Embedded Font Awesome is outdated and conflicts with 5

### ISSUE THREAD

**Issue by namba-r8** [NativeScript/theme#145]
Font Awesome has already updated from 4 to 5, yet `.fa` CSS class defined in the file `theme/app/scss/_icons.scss` is for before 5.

This conflicts with new definition:
``` css
.fa {
    font-family: 'Font Awesome 5 Free', fa-regular-400;
}
```

I think Font Awesome definition should not be placed in this library.
