### ISSUE TITLE
Weird behavior when using theme 2.0

### ISSUE THREAD

**Issue by manijak** [NativeScript/theme#162]
I'm trying to port my app (NS6.0) to use theme 2.0 and seem to be runnin into different issues. Using the following import in my main css:
```css
@import '~nativescript-theme-core/css/core.css';
@import '~nativescript-theme-core/css/blue.css';
```

**First-issue (SegmentedBar):**
Cannot seem to be able to change font color via css, only via XML. This works:
```xml
<SegmentedBar selectedIndex="0" color="white">
      <SegmentedBar.items>
         <SegmentedBarItem title="Fixtures" />
         <SegmentedBarItem title="Results" />
         <SegmentedBarItem title="Table" />
     </SegmentedBar.items>
</SegmentedBar>
```
While this, does not work (`bg-color` and `font-size` applied but _not_ `color`):
```css
SegmentedBar{
    font-size: 14;
    color:#fff;
    background-color: #0362A2;
}
```

**Second issue (Button ignoring `font-familiy` set on `Page`).**
I had to assign `Button` together with `Page` in order to get same font-family:
```css
Page, Button {
    font-family: 'Gotham Rounded', "GothamRounded-Regular";
    font-size: 16;
    color: black;
}
```

**Third issue (Some classes are ignored and not able to override).**
In this case the global `font-size` set on `Page` is **16**. 
The class `fixture-summary` sets the `WrapLayout` `font-size `to **12** (does not work).
The class `fixture-icon` sets the its `font-size `to **14** (does not work).
```xml
<WrapLayout horizontalAlignment="center" margin="5,0,0,0" class="fixture-summary">
     <Label text="" class="fa-font fixture-icon" />
     <Label text="{{ matchDate }}" />
     <Label text=" - " margin="0,5,0,5"/>
     <Label text="" class="fa-font fixture-icon" />
     <Label text="{{ matchTime }}" />
</WrapLayout>
```
Had to change the `fixture-summary` css class to include `Label` for the font-size to be applied. While the `fixture-icon` class only applied the `margin`, ignoring the rest...
```css
.fixture-summary Label {
    font-size: 12;
    color: #4f5b66;
    vertical-align: middle;
}
.fixture-icon{
    font-size: 14;
    color: #4f5b66;
    margin-right: 4;
}
```

**Comment by bundyo** [comment]
Thanks for the report, I'll check them out.

For some of the issues you may want to adjust your CSS rules specificity, as some of the theme rules may have higher specificity than 1.

**Comment by bundyo** [comment]
Let's go over the issues one by one:

1. You didn't mention, but I guess you're using iOS, since only there the specificity of the `Segmentedbar` color is higher, due to the `.ns-ios` root class used in the selector:
	```css
	.ns-ios SegmentedBar {
		color: ...
	}
	```
	To be able to override such styles for both OSes, you can prefix your selectors with a class - for instance `.ns-root` will be a good call, since it is always set. Something in the lines of:
	```css
	.ns-root SegmentedBar {
		color: ...
	}
	```
	Keep in mind that the dark theme adds another class to the party - `.ns-dark`, so you should to override that too, if you need to change it.

1. Should be fixed in 2.0.5.

1. This again looks like a specificity issue, I'll check it out and comment on it later.

1. This looks like a bug, I'll check it out.
