### ISSUE TITLE
Error: Could not find font file for Roboto Medium

### ISSUE THREAD

**Issue by m-abs** [NativeScript/theme#180]
The theme triggers this error with `tns-core-modules@6.1.1`:
```bash
Error: Could not find font file for Roboto Medium
```

I think it is caused by this line in the theme:
https://github.com/NativeScript/theme/blob/13651d81d900e385c8dfedc45f9c2601ec323b2c/src/scss/core/primitives/_index.scss#L16

I think it should be
```css
.ns-root {
  font-family: sans-serif;
  font-weight: medium;
}
```
