### ISSUE TITLE
CSS shorthand properties like margin gets overriden by margin-bottom

### ISSUE THREAD

**Issue by elonmallin** [NativeScript/theme#233]
**Environment**
 - CLI: 6.1.2
 - Android Runtime: 6.1.2
 - Nativescript with Angular
 - @nativescript/theme

**Describe the bug**
It seems like CSS properties like `margin-bottom: 50px;` override their shorthand counterpart `margin: 0;`. I've only tried on Android with Angular.

**To Reproduce**
1. Create a Nativescript with angular project.
2. Include the `@nativescript/theme`.
3. Create two buttons on a page.
4. Add the `h2` class from the theme and a custom `hello` class on the first button.
5.
```css
.hello {
  margin: 0; /* doesn't remove the bottom margin from the button that has the h2 class. */
  /* margin-bottom: 0; */ /* does remove the bottom margin if uncommented. */
}
```
6. See that the first button has a bottom margin that is only removed if we uncomment the `margin-bottom: 0;`.

**Expected behavior**
Shorthand properties like `margin` should not differ from using `margin-bottom` like it works on the web.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=nGvrVO
Uncomment the `margin-bottom` in *home.component.css* to see that it will remove margin which should already be removed by the `margin: 0` just above it.
