### ISSUE TITLE
How to set the background of ActionBar  to real transparent

### ISSUE THREAD

**Issue by rushairer** [NativeScript/theme#253]
Action Bar can not set background to real transparent.

#000000 can not work in iOS.

``` css
ActionBar,
.nt-action-bar,
.ns-dark ActionBar,
.ns-dark .nt-action-bar {
    background-color: unset;
}
```
Will get an error:
``` shell
Error: Failed to apply property [background-color] with value [unset] to ActionBar(77). Color(file:///node_modules/@nativescript/core/color/color-common.js:28:36)
```
