### ISSUE TITLE
Improvements to how .btn-active works

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#96]
So @TheOriginalJosh & I were chatting in Slack. Currently it kind of sucks that you have to opt into `btn-active` styling. So what if we took the following approach instead.

``` css
.btn {
  color: $the-main-color;
}
.btn:highlighted {
  color: $the-highlighted-color;
}
ScrollView .btn:highlighted {
  color: $the-main-color;
}
```

We’d need to test this, but it might end some of the confusion we currently have around these class names.
